using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using HyperMapper.SourceGenerator.Diagnostics;
using HyperMapper.SourceGenerator.Models;

namespace HyperMapper.SourceGenerator.CodeGen;

/// <summary>
/// v7.1.0: Classification of collection types for code generation.
/// </summary>
internal enum CollectionKind
{
    Unknown,
    Array,
    List,                    // List<T>, IList<T>, ICollection<T>, IEnumerable<T>, IReadOnlyList<T>, IReadOnlyCollection<T>
    HashSet,                 // HashSet<T>, ISet<T>, IReadOnlySet<T>
    SortedSet,               // SortedSet<T>
    ObservableCollection,    // ObservableCollection<T>
    LinkedList,              // LinkedList<T>
    Queue,                   // Queue<T>
    Stack,                   // Stack<T>
    Dictionary,              // Dictionary<K,V>, IDictionary<K,V>, IReadOnlyDictionary<K,V>
}

/// <summary>
/// Generates C# mapping code from MappingDefinitions.
/// </summary>
internal class MappingCodeBuilder
{
    private const string GeneratorName = "HyperMapper.SourceGenerator";
    private const string GeneratorVersion = "7.1.0";

    public string GenerateMapperClass(ProfileInfo profile, Compilation compilation, SourceProductionContext context)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// This code was generated by HyperMapper.SourceGenerator v7.1.0");
        sb.AppendLine("// Do not modify this file manually.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Collections.ObjectModel;");  // v7.1.0: ObservableCollection support
        sb.AppendLine("using System.Linq;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(profile.Namespace))
        {
            sb.AppendLine($"namespace {profile.Namespace};");
            sb.AppendLine();
        }

        // Use FullClassName for nested types to ensure unique class names
        var generatedClassName = string.IsNullOrEmpty(profile.FullClassName)
            ? profile.ClassName
            : profile.FullClassName;

        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Generated mapper methods for {profile.ClassName}");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"[global::System.CodeDom.Compiler.GeneratedCode(\"{GeneratorName}\", \"{GeneratorVersion}\")]");
        sb.AppendLine($"internal static class {generatedClassName}GeneratedMappers");
        sb.AppendLine("{");

        foreach (var mapping in profile.Mappings)
        {
            // v7.1.0: Open generic mappings generate generic methods
            if (mapping.IsOpenGeneric)
            {
                GenerateOpenGenericMappingMethod(sb, mapping);
                sb.AppendLine();

                // Generate collection mapping method for open generics
                GenerateOpenGenericCollectionMappingMethod(sb, mapping);
                sb.AppendLine();
                continue;
            }

            // v7.1.0: Lambda converters can be inlined at compile-time
            if (mapping.HasConverter)
            {
                if (!string.IsNullOrEmpty(mapping.ConverterLambdaExpression))
                {
                    // Generate inline converter method
                    GenerateLambdaConverterMethod(sb, mapping);
                    sb.AppendLine();

                    // Generate collection mapping method for lambda converters
                    GenerateCollectionMappingMethod(sb, mapping);
                    sb.AppendLine();
                }
                // Skip class-based converters - they need runtime
                continue;
            }

            // v7.1.0: Value types (structs) are now fully supported at compile-time
            GenerateMappingMethod(sb, mapping, compilation, context);
            sb.AppendLine();

            // Generate collection mapping method
            GenerateCollectionMappingMethod(sb, mapping);
            sb.AppendLine();
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private void GenerateMappingMethod(
        StringBuilder sb,
        MappingDefinition mapping,
        Compilation compilation,
        SourceProductionContext context)
    {
        var sourceType = mapping.SourceType;
        var destType = mapping.DestinationType;
        var methodName = GetMapperMethodName(mapping.SourceTypeName, mapping.DestinationTypeName);

        // v7.1.0: Support value types (structs)
        var isSourceValueType = mapping.SourceTypeSymbol?.IsValueType == true;
        var isDestValueType = mapping.DestinationTypeSymbol?.IsValueType == true;
        var isSourceNullableValueType = IsNullableValueType(mapping.SourceTypeSymbol);

        // v9.0.0: Check if we have custom constructor or ctor param mappings
        var hasCtorParams = mapping.CtorParamMappings.Count > 0;
        var hasCustomCtor = mapping.HasCustomConstructor && !string.IsNullOrEmpty(mapping.ConstructorLambdaExpression);

        // v7.1.0: Check if we have any PreConditions with extractable expressions
        var hasGeneratablePreConditions = mapping.MemberMappings
            .Any(m => m.HasPreCondition && !string.IsNullOrEmpty(m.PreConditionExpression));

        // v8.1.0: Check if we have any Conditions (post-mapping conditional)
        var hasGeneratableConditions = mapping.MemberMappings
            .Any(m => m.HasCondition && !string.IsNullOrEmpty(m.ConditionExpression));

        // v9.0.0: Check if we have ForPath mappings
        var hasPathMappings = mapping.PathMappings.Count > 0;

        // v10.0.0: Check if any MapFrom has destination parameter
        var hasDestinationParameterMappings = mapping.MemberMappings
            .Any(m => m.HasDestinationParameter);

        // v8.1.0: Need result variable if we have PreConditions OR Conditions
        // v9.0.0: Also need result variable if we have ctor params (to set remaining properties) or path mappings
        // v10.0.0: Also need result variable if we have MapFrom with destination parameter
        var needsResultVariable = hasGeneratablePreConditions || hasGeneratableConditions || hasCtorParams || hasPathMappings || hasDestinationParameterMappings;

        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Maps {sourceType} to {destType}");
        sb.AppendLine($"    /// </summary>");

        // Determine the source variable name to use in property access
        // For nullable value types, we extract .Value first, so use "sourceValue"
        var sourceVarName = isSourceNullableValueType ? "sourceValue" : "source";

        if (isSourceValueType && !isSourceNullableValueType)
        {
            // Non-nullable value type source - no null check needed
            // Return type depends on destination
            var returnType = isDestValueType ? destType : $"{destType}?";
            sb.AppendLine($"    public static {returnType} {methodName}({sourceType} source)");
            sb.AppendLine("    {");

            // v9.0.0: Handle ConstructUsing
            if (hasCustomCtor)
            {
                sb.AppendLine($"        return {mapping.ConstructorLambdaExpression};");
                sb.AppendLine("    }");
                return;
            }

            // v9.0.0: Handle ForCtorParam
            if (hasCtorParams)
            {
                GenerateCtorParamConstruction(sb, mapping, destType, sourceVarName);
            }
            else
            {
                // Use "result" variable if we have PreConditions or Conditions to allow post-initialization assignments
                if (needsResultVariable)
                    sb.AppendLine($"        var result = new {destType}");
                else
                    sb.AppendLine($"        return new {destType}");
                sb.AppendLine("        {");
            }
        }
        else
        {
            // Reference type or nullable value type - standard null handling
            sb.AppendLine($"    [return: global::System.Diagnostics.CodeAnalysis.NotNullIfNotNull(nameof(source))]");
            sb.AppendLine($"    public static {destType}? {methodName}({sourceType}? source)");
            sb.AppendLine("    {");
            sb.AppendLine("        if (source is null) return null;");
            sb.AppendLine();

            // For nullable value types, we need to access .Value
            if (isSourceNullableValueType)
            {
                sb.AppendLine($"        var sourceValue = source.Value;");
            }

            // v9.0.0: Handle ConstructUsing
            if (hasCustomCtor)
            {
                var adjustedExpr = isSourceNullableValueType
                    ? mapping.ConstructorLambdaExpression!.Replace("source.", $"{sourceVarName}.")
                    : mapping.ConstructorLambdaExpression;
                sb.AppendLine($"        return {adjustedExpr};");
                sb.AppendLine("    }");
                return;
            }

            // v9.0.0: Handle ForCtorParam
            if (hasCtorParams)
            {
                GenerateCtorParamConstruction(sb, mapping, destType, sourceVarName);
            }
            else
            {
                // Use "result" variable if we have PreConditions or Conditions to allow post-initialization assignments
                if (needsResultVariable)
                    sb.AppendLine($"        var result = new {destType}");
                else
                    sb.AppendLine($"        return new {destType}");
                sb.AppendLine("        {");
            }
        }

        // If we used ConstructUsing, we already returned
        if (hasCustomCtor)
            return;

        // Get properties from type symbols
        var destProperties = GetWritableProperties(mapping.DestinationTypeSymbol);
        var sourceProperties = GetReadablePropertiesDict(mapping.SourceTypeSymbol);

        // v9.0.0: Build set of properties already mapped via ForCtorParam
        var ctorMappedParams = new HashSet<string>(
            mapping.CtorParamMappings.Select(c => c.ParameterName),
            StringComparer.OrdinalIgnoreCase);

        // Build lookup for custom mappings
        var ignoredMembers = new HashSet<string>(
            mapping.MemberMappings.Where(m => m.IsIgnored).Select(m => m.DestinationMember),
            StringComparer.Ordinal);

        var customMappings = mapping.MemberMappings
            .Where(m => !m.IsIgnored && m.SourceExpression != null)
            .ToDictionary(m => m.DestinationMember, m => m.SourceExpression!, StringComparer.Ordinal);

        // v7.1.0: Build PreCondition lookup with expressions
        var preConditionMappings = mapping.MemberMappings
            .Where(m => m.HasPreCondition && !string.IsNullOrEmpty(m.PreConditionExpression))
            .ToDictionary(m => m.DestinationMember, m => m, StringComparer.Ordinal);

        // v8.1.0: Build NullSubstitute lookup
        var nullSubstituteMappings = mapping.MemberMappings
            .Where(m => m.HasNullSubstitute && !string.IsNullOrEmpty(m.NullSubstituteExpression))
            .ToDictionary(m => m.DestinationMember, m => m.NullSubstituteExpression!, StringComparer.Ordinal);

        // v8.1.0: Build Condition lookup (post-mapping conditional)
        var conditionMappings = mapping.MemberMappings
            .Where(m => m.HasCondition && !string.IsNullOrEmpty(m.ConditionExpression))
            .ToDictionary(m => m.DestinationMember, m => m, StringComparer.Ordinal);

        // v10.0.0: Build transform lookup by type
        var transformsByType = mapping.Transforms
            .GroupBy(t => NormalizeTypeName(t.TargetType))
            .ToDictionary(g => g.Key, g => g.First().TransformExpression, StringComparer.Ordinal);

        // v10.0.0: Build lookup for MapFrom with destination parameter (needs result variable)
        var destParamMappings = mapping.MemberMappings
            .Where(m => m.HasDestinationParameter && !string.IsNullOrEmpty(m.SourceExpression))
            .ToDictionary(m => m.DestinationMember, m => m, StringComparer.Ordinal);

        // Generate property assignments for non-PreCondition and non-Condition properties
        foreach (var destProp in destProperties)
        {
            // Skip if ignored
            if (ignoredMembers.Contains(destProp.Name))
                continue;

            // Skip if has precondition (handled separately)
            if (preConditionMappings.ContainsKey(destProp.Name))
                continue;

            // Skip if has condition (handled separately after object initialization)
            if (conditionMappings.ContainsKey(destProp.Name))
                continue;

            // v10.0.0: Skip if has destination parameter (handled separately after object initialization)
            if (destParamMappings.ContainsKey(destProp.Name))
                continue;

            // v9.0.0: Skip if already mapped via ForCtorParam
            if (ctorMappedParams.Contains(destProp.Name))
                continue;

            string? assignment = null;

            if (customMappings.TryGetValue(destProp.Name, out var sourceExpr))
            {
                // Custom MapFrom expression - replace "source." with the correct var name
                var adjustedExpr = isSourceNullableValueType
                    ? sourceExpr.Replace("source.", $"{sourceVarName}.")
                    : sourceExpr;
                assignment = GenerateCustomMappingAssignment(destProp, adjustedExpr);
            }
            else if (sourceProperties.TryGetValue(destProp.Name, out var sourceProp))
            {
                // Convention-based mapping - same name
                assignment = GeneratePropertyAssignment(destProp, sourceProp, mapping, sourceVarName);
            }
            else
            {
                // Try flattening (e.g., AddressStreet -> Address.Street)
                assignment = TryGenerateFlatteningAssignment(destProp, sourceProperties, mapping.SourceTypeSymbol, sourceVarName);

                // v10.0.0: Try IncludeMembers - look for property in included member objects
                if (assignment == null && mapping.IncludedMembers.Count > 0)
                {
                    assignment = TryGenerateIncludeMembersAssignment(destProp, sourceProperties, mapping.IncludedMembers, sourceVarName);
                }
            }

            if (assignment != null)
            {
                // Extract the value expression from the assignment (e.g., "Name = source.Name" -> "source.Name")
                var equalIdx = assignment.IndexOf('=');
                var valueExpr = assignment.Substring(equalIdx + 1).Trim();

                // v10.0.0: Apply AddTransform if configured for this type
                if (transformsByType.Count > 0 && sourceProperties.TryGetValue(destProp.Name, out var srcPropForTransform))
                {
                    valueExpr = ApplyTransform(valueExpr, srcPropForTransform.Type, transformsByType);
                }

                // v8.1.0: Apply NullSubstitute if configured
                if (nullSubstituteMappings.TryGetValue(destProp.Name, out var nullSubstExpr))
                {
                    valueExpr = $"{valueExpr} ?? {nullSubstExpr}";
                }

                assignment = $"{destProp.Name} = {valueExpr}";

                // v9.0.0: If using ForCtorParam, assign directly to result instead of object initializer
                if (hasCtorParams)
                {
                    sb.AppendLine($"        result.{assignment};");
                }
                else
                {
                    sb.AppendLine($"            {assignment},");
                }
            }
        }

        // v9.0.0: Close object initializer only if not using ForCtorParam
        if (!hasCtorParams)
        {
            sb.AppendLine("        };");
        }

        // v7.1.0: Generate conditional assignments for PreCondition properties
        foreach (var kvp in preConditionMappings)
        {
            var destPropName = kvp.Key;
            var memberMapping = kvp.Value;

            // Find the destination property
            var destProp = destProperties.FirstOrDefault(p => p.Name == destPropName);
            if (destProp == null) continue;

            // Adjust PreCondition expression for nullable value types
            var preCondExpr = isSourceNullableValueType
                ? memberMapping.PreConditionExpression!.Replace("source.", $"{sourceVarName}.")
                : memberMapping.PreConditionExpression!;

            // Generate the value expression
            string? valueExpr = null;
            if (memberMapping.SourceExpression != null)
            {
                // Custom MapFrom expression
                var adjustedExpr = isSourceNullableValueType
                    ? memberMapping.SourceExpression.Replace("source.", $"{sourceVarName}.")
                    : memberMapping.SourceExpression;
                valueExpr = adjustedExpr;
            }
            else if (sourceProperties.TryGetValue(destPropName, out var sourceProp))
            {
                // Convention-based mapping
                valueExpr = $"{sourceVarName}.{sourceProp.Name}";
            }

            if (valueExpr != null)
            {
                // v10.0.0: Apply AddTransform if configured for this type
                if (transformsByType.Count > 0 && sourceProperties.TryGetValue(destPropName, out var srcPropForTransform))
                {
                    valueExpr = ApplyTransform(valueExpr, srcPropForTransform.Type, transformsByType);
                }

                // v8.1.0: Apply NullSubstitute if configured
                if (nullSubstituteMappings.TryGetValue(destPropName, out var nullSubstExpr))
                {
                    valueExpr = $"({valueExpr}) ?? {nullSubstExpr}";
                }

                sb.AppendLine();
                sb.AppendLine($"        if ({preCondExpr})");
                sb.AppendLine($"            result.{destPropName} = {valueExpr};");
            }
        }

        // v8.1.0: Generate conditional assignments for Condition properties (post-mapping conditional)
        foreach (var kvp in conditionMappings)
        {
            var destPropName = kvp.Key;
            var memberMapping = kvp.Value;

            // Find the destination property
            var destProp = destProperties.FirstOrDefault(p => p.Name == destPropName);
            if (destProp == null) continue;

            // Generate the value expression
            string? valueExpr = null;
            if (memberMapping.SourceExpression != null)
            {
                // Custom MapFrom expression
                var adjustedExpr = isSourceNullableValueType
                    ? memberMapping.SourceExpression.Replace("source.", $"{sourceVarName}.")
                    : memberMapping.SourceExpression;
                valueExpr = adjustedExpr;
            }
            else if (sourceProperties.TryGetValue(destPropName, out var sourceProp))
            {
                // Convention-based mapping
                valueExpr = $"{sourceVarName}.{sourceProp.Name}";
            }

            if (valueExpr != null)
            {
                // v10.0.0: Apply AddTransform if configured for this type
                if (transformsByType.Count > 0 && sourceProperties.TryGetValue(destPropName, out var srcPropForTransform2))
                {
                    valueExpr = ApplyTransform(valueExpr, srcPropForTransform2.Type, transformsByType);
                }

                // v8.1.0: Apply NullSubstitute if configured (before condition check)
                if (nullSubstituteMappings.TryGetValue(destPropName, out var nullSubstExpr))
                {
                    valueExpr = $"({valueExpr}) ?? {nullSubstExpr}";
                }

                // Adjust Condition expression for nullable value types
                var condExpr = isSourceNullableValueType
                    ? memberMapping.ConditionExpression!.Replace("source.", $"{sourceVarName}.")
                    : memberMapping.ConditionExpression!;

                sb.AppendLine();
                sb.AppendLine($"        var _value = {valueExpr};");
                sb.AppendLine($"        if ({condExpr})");
                sb.AppendLine($"            result.{destPropName} = _value;");
            }
        }

        // v10.0.0: Generate MapFrom with destination parameter assignments
        foreach (var kvp in destParamMappings)
        {
            var destPropName = kvp.Key;
            var memberMapping = kvp.Value;

            var valueExpr = isSourceNullableValueType
                ? memberMapping.SourceExpression!.Replace("source.", $"{sourceVarName}.")
                : memberMapping.SourceExpression!;

            sb.AppendLine();
            sb.AppendLine($"        result.{destPropName} = {valueExpr};");
        }

        // v9.0.0: Generate ForPath assignments
        if (mapping.PathMappings.Count > 0)
        {
            GeneratePathMappings(sb, mapping, sourceVarName, isSourceNullableValueType);
        }

        // If we have PreConditions or Conditions, we used a "result" variable
        if (needsResultVariable)
        {
            sb.AppendLine();
            sb.AppendLine("        return result;");
        }

        sb.AppendLine("    }");
    }

    /// <summary>
    /// v9.0.0: Generates ForPath assignments with intermediate object creation.
    /// </summary>
    private void GeneratePathMappings(
        StringBuilder sb,
        MappingDefinition mapping,
        string sourceVarName,
        bool isSourceNullableValueType)
    {
        // Group path mappings by their first segment to handle intermediate object creation
        var createdIntermediates = new HashSet<string>();

        foreach (var pathMapping in mapping.PathMappings)
        {
            if (pathMapping.IsIgnored || pathMapping.PathSegments.Count == 0)
                continue;

            sb.AppendLine();

            // Build the full path and create intermediate objects if needed
            var currentPath = "result";
            for (int i = 0; i < pathMapping.PathSegments.Count - 1; i++)
            {
                var segment = pathMapping.PathSegments[i];
                var nextPath = $"{currentPath}.{segment}";
                var intermediateKey = string.Join(".", pathMapping.PathSegments.Take(i + 1));

                if (!createdIntermediates.Contains(intermediateKey))
                {
                    // Get the type of this intermediate property from the destination type symbol
                    var propType = GetNestedPropertyType(mapping.DestinationTypeSymbol, pathMapping.PathSegments.Take(i + 1).ToList());

                    if (propType != null && !propType.IsValueType)
                    {
                        sb.AppendLine($"        if ({nextPath} == null)");
                        sb.AppendLine($"            {nextPath} = new {propType.ToDisplayString()}();");
                    }
                    createdIntermediates.Add(intermediateKey);
                }
                currentPath = nextPath;
            }

            // Assign the final value
            var lastSegment = pathMapping.PathSegments.Last();
            var fullPath = $"result.{string.Join(".", pathMapping.PathSegments)}";

            var sourceExpr = pathMapping.SourceExpression ?? $"{sourceVarName}.{lastSegment}";
            if (sourceExpr.StartsWith("source.") && sourceVarName != "source")
            {
                sourceExpr = sourceExpr.Replace("source.", $"{sourceVarName}.");
            }

            sb.AppendLine($"        {fullPath} = {sourceExpr};");
        }
    }

    /// <summary>
    /// v9.0.0: Gets the type of a nested property from path segments.
    /// </summary>
    private static ITypeSymbol? GetNestedPropertyType(ITypeSymbol? typeSymbol, List<string> pathSegments)
    {
        if (typeSymbol == null) return null;

        var currentType = typeSymbol;
        foreach (var segment in pathSegments)
        {
            var prop = currentType.GetMembers()
                .OfType<IPropertySymbol>()
                .FirstOrDefault(p => p.Name == segment);

            if (prop == null) return null;
            currentType = prop.Type;
        }

        return currentType;
    }

    /// <summary>
    /// v9.0.0: Generates constructor invocation with named parameters from ForCtorParam mappings.
    /// </summary>
    private void GenerateCtorParamConstruction(
        StringBuilder sb,
        MappingDefinition mapping,
        string destType,
        string sourceVarName)
    {
        // Generate: var result = new DestType(
        //     paramName: sourceExpr,
        //     ...
        // );
        sb.AppendLine($"        var result = new {destType}(");

        var ctorParams = mapping.CtorParamMappings;
        for (int i = 0; i < ctorParams.Count; i++)
        {
            var param = ctorParams[i];
            var sourceExpr = param.SourceExpression ?? $"{sourceVarName}.{param.ParameterName}";

            // Adjust source expression for the correct variable name
            if (sourceExpr.StartsWith("source.") && sourceVarName != "source")
            {
                sourceExpr = sourceExpr.Replace("source.", $"{sourceVarName}.");
            }

            var comma = i < ctorParams.Count - 1 ? "," : "";
            sb.AppendLine($"            {param.ParameterName}: {sourceExpr}{comma}");
        }

        sb.AppendLine("        );");
        sb.AppendLine();

        // Now we need to also set any remaining properties via object initializer
        // This is done by the calling code after GenerateCtorParamConstruction
        // The calling code should NOT generate "        {" since we already have the object
    }

    /// <summary>
    /// v7.1.0: Generates a mapping method from a lambda converter expression.
    /// </summary>
    private void GenerateLambdaConverterMethod(StringBuilder sb, MappingDefinition mapping)
    {
        var sourceType = mapping.SourceType;
        var destType = mapping.DestinationType;
        var methodName = GetMapperMethodName(mapping.SourceTypeName, mapping.DestinationTypeName);
        var converterExpr = mapping.ConverterLambdaExpression!;

        var isSourceValueType = mapping.SourceTypeSymbol?.IsValueType == true;
        var isSourceNullableValueType = IsNullableValueType(mapping.SourceTypeSymbol);

        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Maps {sourceType} to {destType} using inline converter");
        sb.AppendLine($"    /// </summary>");

        if (isSourceValueType && !isSourceNullableValueType)
        {
            // Non-nullable value type source - no null check needed
            sb.AppendLine($"    public static {destType}? {methodName}({sourceType} source)");
            sb.AppendLine("    {");
            sb.AppendLine($"        return {converterExpr};");
            sb.AppendLine("    }");
        }
        else
        {
            // Reference type or nullable value type - standard null handling
            sb.AppendLine($"    [return: global::System.Diagnostics.CodeAnalysis.NotNullIfNotNull(nameof(source))]");
            sb.AppendLine($"    public static {destType}? {methodName}({sourceType}? source)");
            sb.AppendLine("    {");
            sb.AppendLine("        if (source is null) return null;");

            // For nullable value types, extract .Value
            if (isSourceNullableValueType)
            {
                var adjustedExpr = converterExpr.Replace("source.", "source.Value.");
                sb.AppendLine($"        return {adjustedExpr};");
            }
            else
            {
                sb.AppendLine($"        return {converterExpr};");
            }
            sb.AppendLine("    }");
        }
    }

    private string GenerateCustomMappingAssignment(IPropertySymbol destProp, string sourceExpr)
    {
        // The expression should already have "source." prefixed from the ReplaceParameterWithSource call
        // Optimize the expression before using it
        var optimizedExpr = OptimizeNavigationExpression(sourceExpr);
        return $"{destProp.Name} = {optimizedExpr}";
    }

    /// <summary>
    /// Optimizes navigation expressions to reduce duplicate property access.
    /// Transforms: source.A.B != null ? source.A.B.C : default
    /// Into: source.A.B?.C ?? default
    /// </summary>
    private string OptimizeNavigationExpression(string expression)
    {
        // Pattern: captures "source.X.Y != null ? source.X.Y.Z : <default>"
        // where X.Y is accessed twice (null check + property access)
        // Regex groups:
        // 1: navigation path (e.g., "source.Sub.SubSub")
        // 2: property name after the duplicate navigation (e.g., "IAmACoolProperty")
        // 3: default value (e.g., "string.Empty" or "default" or "null")
        var ternaryPattern = @"(\w+(?:\.\w+)+)\s*!=\s*null\s*\?\s*\1\.(\w+)\s*:\s*(.+)";
        var match = Regex.Match(expression, ternaryPattern);

        if (match.Success)
        {
            var navigationPath = match.Groups[1].Value; // e.g., "source.Sub.SubSub"
            var propertyName = match.Groups[2].Value;    // e.g., "IAmACoolProperty"
            var defaultValue = match.Groups[3].Value.Trim(); // e.g., "string.Empty"

            // Transform to: source.Sub.SubSub?.IAmACoolProperty ?? string.Empty
            return $"{navigationPath}?.{propertyName} ?? {defaultValue}";
        }

        // If pattern doesn't match, return original expression unchanged
        return expression;
    }

    private string? GeneratePropertyAssignment(
        IPropertySymbol destProp,
        IPropertySymbol sourceProp,
        MappingDefinition mapping,
        string sourceVarName = "source")
    {
        var destType = destProp.Type;
        var sourceType = sourceProp.Type;

        // Same type - direct assignment
        if (SymbolEqualityComparer.Default.Equals(destType, sourceType))
        {
            return $"{destProp.Name} = {sourceVarName}.{sourceProp.Name}";
        }

        // Both nullable or both non-nullable of same underlying type
        var destUnderlying = GetUnderlyingType(destType);
        var sourceUnderlying = GetUnderlyingType(sourceType);

        // T -> T? (implicit conversion)
        if (destUnderlying != null && SymbolEqualityComparer.Default.Equals(destUnderlying, sourceType))
        {
            return $"{destProp.Name} = {sourceVarName}.{sourceProp.Name}";
        }

        // T? -> T (need null check or default)
        if (sourceUnderlying != null && SymbolEqualityComparer.Default.Equals(sourceUnderlying, destType))
        {
            if (destType.IsValueType)
            {
                return $"{destProp.Name} = {sourceVarName}.{sourceProp.Name} ?? default";
            }
            else
            {
                return $"{destProp.Name} = {sourceVarName}.{sourceProp.Name}!";
            }
        }

        // Enum to string
        if (sourceType.TypeKind == TypeKind.Enum && destType.SpecialType == SpecialType.System_String)
        {
            return $"{destProp.Name} = {sourceVarName}.{sourceProp.Name}.ToString()";
        }

        // String to enum
        if (sourceType.SpecialType == SpecialType.System_String && destType.TypeKind == TypeKind.Enum)
        {
            return $"{destProp.Name} = Enum.Parse<{destType.ToDisplayString()}>({sourceVarName}.{sourceProp.Name})";
        }

        // Numeric conversions
        if (IsNumericType(sourceType) && IsNumericType(destType))
        {
            return $"{destProp.Name} = ({destType.ToDisplayString()}){sourceVarName}.{sourceProp.Name}";
        }

        // v7.1.0: Dictionary mapping (before general collection check)
        if (IsDictionaryType(sourceType) && IsDictionaryType(destType))
        {
            return GenerateDictionaryPropertyAssignment(destProp, sourceProp, sourceVarName);
        }

        // Collection mapping
        if (IsCollectionType(sourceType) && IsCollectionType(destType))
        {
            return GenerateCollectionPropertyAssignment(destProp, sourceProp, sourceVarName);
        }

        // Nested complex type - try to find a generated mapper
        if (IsComplexType(sourceType) && IsComplexType(destType))
        {
            var nestedMethodName = GetMapperMethodName(sourceType.Name, destType.Name);
            return $"{destProp.Name} = {nestedMethodName}({sourceVarName}.{sourceProp.Name})";
        }

        // Assignable (implicit conversion)
        if (compilation_IsAssignable(sourceType, destType))
        {
            return $"{destProp.Name} = {sourceVarName}.{sourceProp.Name}";
        }

        // Can't map - return null (property will be skipped)
        return null;
    }

    /// <summary>
    /// v7.1.0: Generates collection property assignment with support for all collection types.
    /// </summary>
    private string? GenerateCollectionPropertyAssignment(IPropertySymbol destProp, IPropertySymbol sourceProp, string sourceVarName = "source")
    {
        // v7.1.0: Handle dictionary types separately
        if (IsDictionaryType(destProp.Type))
        {
            return GenerateDictionaryPropertyAssignment(destProp, sourceProp, sourceVarName);
        }

        var destElementType = GetCollectionElementType(destProp.Type);
        var sourceElementType = GetCollectionElementType(sourceProp.Type);

        if (destElementType == null || sourceElementType == null)
        {
            return $"{destProp.Name} = {sourceVarName}.{sourceProp.Name}?.ToList() ?? new()";
        }

        var destKind = GetCollectionKind(destProp.Type);
        var destElemStr = destElementType.ToDisplayString();
        var sourceExpr = $"{sourceVarName}.{sourceProp.Name}";

        // Same element type
        if (SymbolEqualityComparer.Default.Equals(destElementType, sourceElementType))
        {
            return GenerateSameTypeCollectionAssignment(destProp.Name, sourceExpr, destElemStr, destKind);
        }

        // Simple types that can be converted
        if (IsSimpleType(sourceElementType) && IsSimpleType(destElementType))
        {
            var convertExpr = $"{sourceExpr}?.Select(x => ({destElemStr})x)";
            return GenerateConvertedCollectionAssignment(destProp.Name, convertExpr, destElemStr, destKind);
        }

        // Different element types - need mapping
        var elementMethodName = GetMapperMethodName(sourceElementType.Name, destElementType.Name);
        return GenerateMappedCollectionAssignment(destProp.Name, sourceExpr, destElemStr, elementMethodName, destKind);
    }

    /// <summary>
    /// v7.1.0: Generates assignment for same-type collections.
    /// </summary>
    private static string GenerateSameTypeCollectionAssignment(
        string destPropName, string sourceExpr, string elemType, CollectionKind kind)
    {
        return kind switch
        {
            // Array
            CollectionKind.Array =>
                $"{destPropName} = {sourceExpr}?.ToArray() ?? Array.Empty<{elemType}>()",

            // HashSet
            CollectionKind.HashSet =>
                $"{destPropName} = {sourceExpr} != null ? new HashSet<{elemType}>({sourceExpr}) : new HashSet<{elemType}>()",

            // SortedSet
            CollectionKind.SortedSet =>
                $"{destPropName} = {sourceExpr} != null ? new SortedSet<{elemType}>({sourceExpr}) : new SortedSet<{elemType}>()",

            // ObservableCollection
            CollectionKind.ObservableCollection =>
                $"{destPropName} = {sourceExpr} != null ? new ObservableCollection<{elemType}>({sourceExpr}) : new ObservableCollection<{elemType}>()",

            // LinkedList
            CollectionKind.LinkedList =>
                $"{destPropName} = {sourceExpr} != null ? new LinkedList<{elemType}>({sourceExpr}) : new LinkedList<{elemType}>()",

            // Queue (FIFO order preserved)
            CollectionKind.Queue =>
                $"{destPropName} = {sourceExpr} != null ? new Queue<{elemType}>({sourceExpr}) : new Queue<{elemType}>()",

            // Stack (MUST REVERSE to preserve order!)
            CollectionKind.Stack =>
                $"{destPropName} = {sourceExpr} != null ? new Stack<{elemType}>({sourceExpr}.Reverse()) : new Stack<{elemType}>()",

            // List-like (default) - use ToList
            _ => $"{destPropName} = {sourceExpr}?.ToList() ?? new List<{elemType}>()"
        };
    }

    /// <summary>
    /// v7.1.0: Generates assignment for converted (cast) collections.
    /// </summary>
    private static string GenerateConvertedCollectionAssignment(
        string destPropName, string convertExpr, string destElemType, CollectionKind kind)
    {
        return kind switch
        {
            CollectionKind.Array =>
                $"{destPropName} = {convertExpr}?.ToArray() ?? Array.Empty<{destElemType}>()",

            CollectionKind.HashSet =>
                $"{destPropName} = {convertExpr} != null ? new HashSet<{destElemType}>({convertExpr}) : new HashSet<{destElemType}>()",

            CollectionKind.SortedSet =>
                $"{destPropName} = {convertExpr} != null ? new SortedSet<{destElemType}>({convertExpr}) : new SortedSet<{destElemType}>()",

            CollectionKind.ObservableCollection =>
                $"{destPropName} = {convertExpr} != null ? new ObservableCollection<{destElemType}>({convertExpr}) : new ObservableCollection<{destElemType}>()",

            CollectionKind.LinkedList =>
                $"{destPropName} = {convertExpr} != null ? new LinkedList<{destElemType}>({convertExpr}) : new LinkedList<{destElemType}>()",

            CollectionKind.Queue =>
                $"{destPropName} = {convertExpr} != null ? new Queue<{destElemType}>({convertExpr}) : new Queue<{destElemType}>()",

            CollectionKind.Stack =>
                $"{destPropName} = {convertExpr} != null ? new Stack<{destElemType}>({convertExpr}.Reverse()) : new Stack<{destElemType}>()",

            _ => $"{destPropName} = {convertExpr}?.ToList() ?? new List<{destElemType}>()"
        };
    }

    /// <summary>
    /// v7.1.0: Generates assignment for mapped collections (different element types).
    /// </summary>
    private static string GenerateMappedCollectionAssignment(
        string destPropName, string sourceExpr, string destElemType,
        string mapperMethodName, CollectionKind kind)
    {
        // v10.0.0: Use lambda with null-forgiving operator to ensure non-nullable element type
        // This avoids CS8619 warnings about List<T?> vs List<T> nullability mismatches
        var selectExpr = $"{sourceExpr}?.Select(x => {mapperMethodName}(x)!)";

        return kind switch
        {
            CollectionKind.Array =>
                $"{destPropName} = {selectExpr}?.ToArray() ?? Array.Empty<{destElemType}>()",

            CollectionKind.HashSet =>
                $"{destPropName} = {selectExpr} != null ? new HashSet<{destElemType}>({selectExpr}) : new HashSet<{destElemType}>()",

            CollectionKind.SortedSet =>
                $"{destPropName} = {selectExpr} != null ? new SortedSet<{destElemType}>({selectExpr}) : new SortedSet<{destElemType}>()",

            CollectionKind.ObservableCollection =>
                $"{destPropName} = {selectExpr} != null ? new ObservableCollection<{destElemType}>({selectExpr}) : new ObservableCollection<{destElemType}>()",

            CollectionKind.LinkedList =>
                $"{destPropName} = {selectExpr} != null ? new LinkedList<{destElemType}>({selectExpr}) : new LinkedList<{destElemType}>()",

            CollectionKind.Queue =>
                $"{destPropName} = {selectExpr} != null ? new Queue<{destElemType}>({selectExpr}) : new Queue<{destElemType}>()",

            // Stack: reverse AFTER mapping to preserve order
            CollectionKind.Stack =>
                $"{destPropName} = {selectExpr} != null ? new Stack<{destElemType}>({selectExpr}.Reverse()) : new Stack<{destElemType}>()",

            _ => $"{destPropName} = {selectExpr}?.ToList() ?? new List<{destElemType}>()"
        };
    }

    /// <summary>
    /// v7.1.0: Generates dictionary property assignment.
    /// </summary>
    private string? GenerateDictionaryPropertyAssignment(IPropertySymbol destProp, IPropertySymbol sourceProp, string sourceVarName)
    {
        var (destKeyType, destValueType) = GetDictionaryKeyValueTypes(destProp.Type);
        var (sourceKeyType, sourceValueType) = GetDictionaryKeyValueTypes(sourceProp.Type);

        if (destKeyType == null || destValueType == null || sourceKeyType == null || sourceValueType == null)
            return null;

        var destKeyStr = destKeyType.ToDisplayString();
        var destValueStr = destValueType.ToDisplayString();
        var sourceExpr = $"{sourceVarName}.{sourceProp.Name}";

        // Same key AND value types - direct copy
        if (SymbolEqualityComparer.Default.Equals(destKeyType, sourceKeyType) &&
            SymbolEqualityComparer.Default.Equals(destValueType, sourceValueType))
        {
            return $"{destProp.Name} = {sourceExpr} != null ? new Dictionary<{destKeyStr}, {destValueStr}>({sourceExpr}) : new Dictionary<{destKeyStr}, {destValueStr}>()";
        }

        // Same keys, different values (need value mapping)
        if (SymbolEqualityComparer.Default.Equals(destKeyType, sourceKeyType))
        {
            // Check if value is a simple type conversion
            if (IsSimpleType(sourceValueType) && IsSimpleType(destValueType))
            {
                return $"{destProp.Name} = {sourceExpr} != null ? {sourceExpr}.ToDictionary(kvp => kvp.Key, kvp => ({destValueStr})kvp.Value) : new Dictionary<{destKeyStr}, {destValueStr}>()";
            }

            // Complex value type - need mapper
            var valueMapperName = GetMapperMethodName(sourceValueType.Name, destValueType.Name);
            return $"{destProp.Name} = {sourceExpr} != null ? {sourceExpr}.ToDictionary(kvp => kvp.Key, kvp => {valueMapperName}(kvp.Value)!) : new Dictionary<{destKeyStr}, {destValueStr}>()";
        }

        // Different key types - not supported at compile-time, skip
        return null;
    }

    /// <summary>
    /// v10.0.0: Tries to generate assignment from IncludeMembers.
    /// Looks for matching property in nested member objects.
    /// </summary>
    private string? TryGenerateIncludeMembersAssignment(
        IPropertySymbol destProp,
        Dictionary<string, IPropertySymbol> sourceProperties,
        List<string> includedMembers,
        string sourceVarName = "source")
    {
        var destName = destProp.Name;

        foreach (var memberName in includedMembers)
        {
            if (!sourceProperties.TryGetValue(memberName, out var memberProp))
                continue;

            // Look for a property with the same name in the member object
            var nestedProp = GetPropertyByName(memberProp.Type, destName);
            if (nestedProp != null)
            {
                // Generate null-safe access: source.Member?.Property
                return $"{destProp.Name} = {sourceVarName}.{memberName}?.{destName}";
            }
        }

        return null;
    }

    private string? TryGenerateFlatteningAssignment(
        IPropertySymbol destProp,
        Dictionary<string, IPropertySymbol> sourceProperties,
        ITypeSymbol? sourceTypeSymbol,
        string sourceVarName = "source")
    {
        if (sourceTypeSymbol == null) return null;

        // Try to find nested property (e.g., AddressStreet -> Address.Street)
        var destName = destProp.Name;

        foreach (var kvp in sourceProperties)
        {
            var sourceName = kvp.Key;
            var sourceProp = kvp.Value;

            if (destName.StartsWith(sourceName, StringComparison.Ordinal) &&
                destName.Length > sourceName.Length)
            {
                var remainingName = destName.Substring(sourceName.Length);

                // Check if source property has a nested property with remaining name
                var nestedProp = GetPropertyByName(sourceProp.Type, remainingName);
                if (nestedProp != null)
                {
                    // Generate null-safe access
                    return $"{destProp.Name} = {sourceVarName}.{sourceName}?.{remainingName}";
                }
            }
        }

        return null;
    }

    /// <summary>
    /// v7.1.0: Generates a generic mapping method for open generic types.
    /// </summary>
    private void GenerateOpenGenericMappingMethod(StringBuilder sb, MappingDefinition mapping)
    {
        if (!mapping.IsOpenGeneric || mapping.TypeParameters == null || mapping.OpenSourceType == null || mapping.OpenDestType == null)
            return;

        var methodName = GetMapperMethodName(mapping.SourceTypeName, mapping.DestinationTypeName);
        var typeParamsDecl = string.Join(", ", mapping.TypeParameters);
        var sourceType = mapping.OpenSourceType;
        var destType = mapping.OpenDestType;

        // Get properties from type symbols
        var sourceProps = GetWritableProperties(mapping.SourceTypeSymbol).ToList();
        var destProps = GetWritableProperties(mapping.DestinationTypeSymbol).ToList();

        // Build lookup of source properties by name
        var sourcePropsDict = sourceProps.ToDictionary(p => p.Name, StringComparer.OrdinalIgnoreCase);

        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Maps {sourceType} to {destType} (open generic)");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    [return: global::System.Diagnostics.CodeAnalysis.NotNullIfNotNull(nameof(source))]");
        sb.AppendLine($"    public static {destType}? {methodName}<{typeParamsDecl}>({sourceType}? source)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (source is null) return null;");
        sb.AppendLine($"        return new {destType}");
        sb.AppendLine("        {");

        var assignments = new List<string>();
        foreach (var destProp in destProps)
        {
            if (sourcePropsDict.TryGetValue(destProp.Name, out var sourceProp))
            {
                var assignment = GenerateOpenGenericPropertyAssignment(destProp, sourceProp, mapping.TypeParameters);
                if (assignment != null)
                {
                    assignments.Add(assignment);
                }
            }
        }

        for (int i = 0; i < assignments.Count; i++)
        {
            var suffix = i < assignments.Count - 1 ? "," : "";
            sb.AppendLine($"            {assignments[i]}{suffix}");
        }

        sb.AppendLine("        };");
        sb.AppendLine("    }");
    }

    /// <summary>
    /// v7.1.0: Generates a property assignment for open generic mappings.
    /// </summary>
    private string? GenerateOpenGenericPropertyAssignment(IPropertySymbol destProp, IPropertySymbol sourceProp, List<string> typeParameters)
    {
        // For open generics, we check if types are compatible
        var destType = destProp.Type;
        var sourceType = sourceProp.Type;

        // Same type (including type parameters) - direct assignment
        if (SymbolEqualityComparer.Default.Equals(destType, sourceType))
        {
            return $"{destProp.Name} = source.{sourceProp.Name}";
        }

        // If source is a type parameter (T) and dest is also T, allow assignment
        if (sourceType is ITypeParameterSymbol && destType is ITypeParameterSymbol)
        {
            // Both are type parameters - assume they match (same position)
            return $"{destProp.Name} = source.{sourceProp.Name}";
        }

        // Simple types that are always assignable
        if (IsSimpleType(sourceType) && IsSimpleType(destType))
        {
            if (destType.SpecialType == sourceType.SpecialType)
            {
                return $"{destProp.Name} = source.{sourceProp.Name}";
            }
        }

        // Assignable types
        if (compilation_IsAssignable(sourceType, destType))
        {
            return $"{destProp.Name} = source.{sourceProp.Name}";
        }

        // Can't map automatically - skip
        return null;
    }

    /// <summary>
    /// v7.1.0: Generates a collection mapping method for open generic types.
    /// </summary>
    private void GenerateOpenGenericCollectionMappingMethod(StringBuilder sb, MappingDefinition mapping)
    {
        if (!mapping.IsOpenGeneric || mapping.TypeParameters == null || mapping.OpenSourceType == null || mapping.OpenDestType == null)
            return;

        var methodName = GetMapperMethodName(mapping.SourceTypeName, mapping.DestinationTypeName);
        var typeParamsDecl = string.Join(", ", mapping.TypeParameters);
        var sourceType = mapping.OpenSourceType;
        var destType = mapping.OpenDestType;

        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Maps IEnumerable&lt;{mapping.SourceTypeName}&lt;{typeParamsDecl}&gt;&gt; to List&lt;{mapping.DestinationTypeName}&lt;{typeParamsDecl}&gt;&gt;");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    public static List<{destType}> {methodName}List<{typeParamsDecl}>(IEnumerable<{sourceType}>? source)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (source is null) return new();");
        sb.AppendLine();
        sb.AppendLine($"        var sourceCollection = source as ICollection<{sourceType}> ?? source.ToList();");
        sb.AppendLine($"        var result = new List<{destType}>(sourceCollection.Count);");
        sb.AppendLine();
        sb.AppendLine("        foreach (var item in sourceCollection)");
        sb.AppendLine("        {");
        sb.AppendLine($"            result.Add({methodName}<{typeParamsDecl}>(item)!);");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        return result;");
        sb.AppendLine("    }");
    }

    private void GenerateCollectionMappingMethod(StringBuilder sb, MappingDefinition mapping)
    {
        var sourceType = mapping.SourceType;
        var destType = mapping.DestinationType;
        var methodName = GetMapperMethodName(mapping.SourceTypeName, mapping.DestinationTypeName);

        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Maps IEnumerable&lt;{mapping.SourceTypeName}&gt; to List&lt;{mapping.DestinationTypeName}&gt;");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    public static List<{destType}> {methodName}List(IEnumerable<{sourceType}>? source)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (source is null) return new();");
        sb.AppendLine();
        sb.AppendLine($"        var sourceCollection = source as ICollection<{sourceType}> ?? source.ToList();");
        sb.AppendLine($"        var result = new List<{destType}>(sourceCollection.Count);");
        sb.AppendLine();
        sb.AppendLine("        foreach (var item in sourceCollection)");
        sb.AppendLine("        {");
        sb.AppendLine($"            result.Add({methodName}(item)!);");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        return result;");
        sb.AppendLine("    }");
    }

    public string GenerateRegistryInitializer(IEnumerable<ProfileInfo?> profiles)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// This code was generated by HyperMapper.SourceGenerator v7.1.0");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace HyperMapper.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Registry of all generated mappers. Call Initialize() at startup.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"[global::System.CodeDom.Compiler.GeneratedCode(\"{GeneratorName}\", \"{GeneratorVersion}\")]");
        sb.AppendLine("public static class HyperMapperGeneratedRegistry");
        sb.AppendLine("{");
        sb.AppendLine("    private static bool _initialized;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Registers all generated mappers with the MapperConfiguration.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static void Initialize(HyperMapper.MapperConfiguration config)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (_initialized) return;");
        sb.AppendLine("        _initialized = true;");
        sb.AppendLine();

        foreach (var profile in profiles.Where(p => p != null))
        {
            // Use FullClassName for nested types
            var generatedClassName = string.IsNullOrEmpty(profile!.FullClassName)
                ? profile.ClassName
                : profile.FullClassName;

            foreach (var mapping in profile.Mappings)
            {
                // v7.1.0: Skip open generic mappings - they are handled at runtime
                // The generated generic methods can be called directly but not registered
                if (mapping.IsOpenGeneric)
                    continue;

                // v7.1.0: Include mappings without converters AND lambda converters
                // Skip class-based converters that don't have lambda expressions
                if (mapping.HasConverter && string.IsNullOrEmpty(mapping.ConverterLambdaExpression))
                    continue;

                var methodName = GetMapperMethodName(mapping.SourceTypeName, mapping.DestinationTypeName);
                var mapperClass = string.IsNullOrEmpty(profile.Namespace)
                    ? $"{generatedClassName}GeneratedMappers"
                    : $"{profile.Namespace}.{generatedClassName}GeneratedMappers";

                var comment = mapping.HasConverter
                    ? $"// {mapping.SourceType} -> {mapping.DestinationType} (lambda converter)"
                    : $"// {mapping.SourceType} -> {mapping.DestinationType}";

                sb.AppendLine($"        {comment}");
                sb.AppendLine($"        config.RegisterGeneratedPlan<{mapping.SourceType}, {mapping.DestinationType}>(");
                sb.AppendLine($"            {mapperClass}.{methodName});");
                sb.AppendLine();
            }
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// v11.0.0: Generates a static Mapper class for maximum performance (~21ns).
    /// This is the recommended API for CodeGen - no IMapper overhead.
    /// </summary>
    public string GenerateStaticMapper()
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// This code was generated by HyperMapper.SourceGenerator v11.0.0");
        sb.AppendLine("// Static Mapper API for maximum performance.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine();
        sb.AppendLine("namespace HyperMapper.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Static mapper API for maximum performance (~21ns).");
        sb.AppendLine("/// Equivalent to manual mapping performance.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("/// <remarks>");
        sb.AppendLine("/// Use this for CodeGen - no IMapper interface overhead.");
        sb.AppendLine("/// For IMapper compatibility, use config.CreateMapper() instead.");
        sb.AppendLine("/// </remarks>");
        sb.AppendLine($"[global::System.CodeDom.Compiler.GeneratedCode(\"{GeneratorName}\", \"11.0.0\")]");
        sb.AppendLine("public static class Mapper");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Maps source to destination using compile-time generated code.");
        sb.AppendLine("    /// Performance: ~21ns (equivalent to manual mapping).");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <typeparam name=\"TSource\">Source type</typeparam>");
        sb.AppendLine("    /// <typeparam name=\"TDest\">Destination type</typeparam>");
        sb.AppendLine("    /// <param name=\"source\">Source object to map</param>");
        sb.AppendLine("    /// <returns>Mapped destination object, or default if source is null or mapping not found</returns>");
        sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("    public static TDest? Map<TSource, TDest>(TSource source)");
        sb.AppendLine("        => GeneratedMapperDispatch.MapDirect<TSource, TDest>(source);");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// v8.0.0: Generates direct dispatch class for zero-overhead type switching.
    /// JIT optimizes typeof(T) == typeof(U) to constant true/false, eliminating delegate overhead.
    /// </summary>
    public string GenerateDirectDispatch(IEnumerable<ProfileInfo?> profiles)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// This code was generated by HyperMapper.SourceGenerator v8.0.0");
        sb.AppendLine("// Direct dispatch for zero delegate overhead.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine();
        sb.AppendLine("namespace HyperMapper.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Direct type dispatch without delegate invocation overhead.");
        sb.AppendLine("/// JIT optimizes typeof(T)==typeof(U) checks to zero cost.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"[global::System.CodeDom.Compiler.GeneratedCode(\"{GeneratorName}\", \"{GeneratorVersion}\")]");
        sb.AppendLine("public static class GeneratedMapperDispatch");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Maps source to destination using direct method dispatch.");
        sb.AppendLine("    /// Returns default if no mapping is registered.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("    public static TDest? MapDirect<TSource, TDest>(TSource source)");
        sb.AppendLine("    {");

        var mappingCount = 0;
        foreach (var profile in profiles.Where(p => p != null))
        {
            // Use FullClassName for nested types
            var generatedClassName = string.IsNullOrEmpty(profile!.FullClassName)
                ? profile.ClassName
                : profile.FullClassName;

            var mapperClass = string.IsNullOrEmpty(profile.Namespace)
                ? $"{generatedClassName}GeneratedMappers"
                : $"{profile.Namespace}.{generatedClassName}GeneratedMappers";

            foreach (var mapping in profile.Mappings)
            {
                // Skip open generic mappings - they need runtime type parameters
                if (mapping.IsOpenGeneric)
                    continue;

                // Skip class-based converters that don't have lambda expressions
                if (mapping.HasConverter && string.IsNullOrEmpty(mapping.ConverterLambdaExpression))
                    continue;

                var methodName = GetMapperMethodName(mapping.SourceTypeName, mapping.DestinationTypeName);
                var sourceType = mapping.SourceType;
                var destType = mapping.DestinationType;

                sb.AppendLine($"        // {sourceType} -> {destType}");
                sb.AppendLine($"        if (typeof(TSource) == typeof({sourceType}) &&");
                sb.AppendLine($"            typeof(TDest) == typeof({destType}))");
                sb.AppendLine("        {");

                // v9.0.0: Handle Include<> for polymorphic dispatch
                if (mapping.IncludedDerivedTypes.Count > 0)
                {
                    sb.AppendLine($"            var srcObj = ({sourceType})(object?)source!;");
                    foreach (var (derivedSource, derivedDest) in mapping.IncludedDerivedTypes)
                    {
                        var derivedMethodName = GetMapperMethodName(
                            derivedSource.Contains('.') ? derivedSource.Substring(derivedSource.LastIndexOf('.') + 1) : derivedSource,
                            derivedDest.Contains('.') ? derivedDest.Substring(derivedDest.LastIndexOf('.') + 1) : derivedDest);
                        sb.AppendLine($"            if (srcObj is {derivedSource} derived{derivedSource.Replace(".", "_")})");
                        sb.AppendLine($"                return (TDest?)(object?){mapperClass}.{derivedMethodName}(derived{derivedSource.Replace(".", "_")});");
                    }
                    sb.AppendLine($"            return (TDest?)(object?){mapperClass}.{methodName}(srcObj);");
                }
                else
                {
                    sb.AppendLine($"            return (TDest?)(object?){mapperClass}.{methodName}(({sourceType})(object?)source!);");
                }

                sb.AppendLine("        }");
                sb.AppendLine();
                mappingCount++;
            }
        }

        sb.AppendLine("        // No direct mapping found - return default to trigger fallback");
        sb.AppendLine("        return default;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>Number of direct mappings registered: {mappingCount}</summary>");
        sb.AppendLine($"    public const int MappingCount = {mappingCount};");
        sb.AppendLine("}");

        return sb.ToString();
    }

    #region Helper Methods

    private static string GetMapperMethodName(string sourceTypeName, string destTypeName)
    {
        return $"Map{sourceTypeName}To{destTypeName}";
    }

    private static IEnumerable<IPropertySymbol> GetWritableProperties(ITypeSymbol? typeSymbol)
    {
        if (typeSymbol == null) return Enumerable.Empty<IPropertySymbol>();

        return typeSymbol.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => p.SetMethod != null &&
                        p.SetMethod.DeclaredAccessibility == Accessibility.Public &&
                        !p.IsReadOnly &&
                        !p.IsStatic);
    }

    private static Dictionary<string, IPropertySymbol> GetReadablePropertiesDict(ITypeSymbol? typeSymbol)
    {
        if (typeSymbol == null) return new Dictionary<string, IPropertySymbol>();

        return typeSymbol.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => p.GetMethod != null &&
                        p.GetMethod.DeclaredAccessibility == Accessibility.Public &&
                        !p.IsWriteOnly &&
                        !p.IsStatic)
            .ToDictionary(p => p.Name, p => p, StringComparer.Ordinal);
    }

    private static IPropertySymbol? GetPropertyByName(ITypeSymbol typeSymbol, string name)
    {
        return typeSymbol.GetMembers()
            .OfType<IPropertySymbol>()
            .FirstOrDefault(p => p.Name.Equals(name, StringComparison.Ordinal));
    }

    private static ITypeSymbol? GetUnderlyingType(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol namedType &&
            namedType.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T)
        {
            return namedType.TypeArguments[0];
        }
        return null;
    }

    /// <summary>
    /// Checks if the type is Nullable&lt;T&gt; (e.g., int?, Point?).
    /// </summary>
    private static bool IsNullableValueType(ITypeSymbol? type)
    {
        if (type == null) return false;
        return type is INamedTypeSymbol namedType &&
               namedType.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T;
    }

    private static bool IsNumericType(ITypeSymbol type)
    {
        var underlying = GetUnderlyingType(type) ?? type;
        return underlying.SpecialType switch
        {
            SpecialType.System_Byte => true,
            SpecialType.System_SByte => true,
            SpecialType.System_Int16 => true,
            SpecialType.System_UInt16 => true,
            SpecialType.System_Int32 => true,
            SpecialType.System_UInt32 => true,
            SpecialType.System_Int64 => true,
            SpecialType.System_UInt64 => true,
            SpecialType.System_Single => true,
            SpecialType.System_Double => true,
            SpecialType.System_Decimal => true,
            _ => false
        };
    }

    private static bool IsSimpleType(ITypeSymbol type)
    {
        var underlying = GetUnderlyingType(type) ?? type;
        if (underlying.TypeKind == TypeKind.Enum) return true;

        return underlying.SpecialType switch
        {
            SpecialType.System_Boolean => true,
            SpecialType.System_Byte => true,
            SpecialType.System_SByte => true,
            SpecialType.System_Int16 => true,
            SpecialType.System_UInt16 => true,
            SpecialType.System_Int32 => true,
            SpecialType.System_UInt32 => true,
            SpecialType.System_Int64 => true,
            SpecialType.System_UInt64 => true,
            SpecialType.System_Single => true,
            SpecialType.System_Double => true,
            SpecialType.System_Decimal => true,
            SpecialType.System_Char => true,
            SpecialType.System_String => true,
            SpecialType.System_DateTime => true,
            _ => underlying.ToDisplayString() switch
            {
                "System.Guid" => true,
                "System.DateOnly" => true,
                "System.TimeOnly" => true,
                "System.DateTimeOffset" => true,
                "System.TimeSpan" => true,
                _ => false
            }
        };
    }

    /// <summary>
    /// v7.1.0: Checks if the type is a supported collection type.
    /// Extended to support Dictionary, ObservableCollection, LinkedList, Queue, Stack, SortedSet, ISet, IReadOnlySet.
    /// </summary>
    private static bool IsCollectionType(ITypeSymbol type)
    {
        if (type is IArrayTypeSymbol) return true;

        if (type is INamedTypeSymbol namedType)
        {
            var fullName = namedType.OriginalDefinition.ToDisplayString();
            return
                // Existing v7.0.0 collections
                fullName.StartsWith("System.Collections.Generic.List<") ||
                fullName.StartsWith("System.Collections.Generic.IList<") ||
                fullName.StartsWith("System.Collections.Generic.ICollection<") ||
                fullName.StartsWith("System.Collections.Generic.IEnumerable<") ||
                fullName.StartsWith("System.Collections.Generic.IReadOnlyList<") ||
                fullName.StartsWith("System.Collections.Generic.IReadOnlyCollection<") ||
                fullName.StartsWith("System.Collections.Generic.HashSet<") ||
                // v7.1.0: Additional collections
                fullName.StartsWith("System.Collections.ObjectModel.ObservableCollection<") ||
                fullName.StartsWith("System.Collections.Generic.LinkedList<") ||
                fullName.StartsWith("System.Collections.Generic.Queue<") ||
                fullName.StartsWith("System.Collections.Generic.Stack<") ||
                fullName.StartsWith("System.Collections.Generic.SortedSet<") ||
                fullName.StartsWith("System.Collections.Generic.ISet<") ||
                fullName.StartsWith("System.Collections.Generic.IReadOnlySet<");
        }

        return false;
    }

    /// <summary>
    /// v7.1.0: Checks if the type is a dictionary type.
    /// </summary>
    private static bool IsDictionaryType(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol namedType)
        {
            var fullName = namedType.OriginalDefinition.ToDisplayString();
            return fullName.StartsWith("System.Collections.Generic.Dictionary<") ||
                   fullName.StartsWith("System.Collections.Generic.IDictionary<") ||
                   fullName.StartsWith("System.Collections.Generic.IReadOnlyDictionary<");
        }
        return false;
    }

    /// <summary>
    /// v7.1.0: Gets the key and value types from a dictionary type.
    /// </summary>
    private static (ITypeSymbol? KeyType, ITypeSymbol? ValueType) GetDictionaryKeyValueTypes(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol namedType && namedType.TypeArguments.Length == 2)
            return (namedType.TypeArguments[0], namedType.TypeArguments[1]);
        return (null, null);
    }

    /// <summary>
    /// v7.1.0: Determines the collection kind for code generation.
    /// </summary>
    private static CollectionKind GetCollectionKind(ITypeSymbol type)
    {
        if (type is IArrayTypeSymbol) return CollectionKind.Array;

        if (type is INamedTypeSymbol namedType)
        {
            var fullName = namedType.OriginalDefinition.ToDisplayString();

            // Dictionary types (2 type parameters)
            if (fullName.StartsWith("System.Collections.Generic.Dictionary<") ||
                fullName.StartsWith("System.Collections.Generic.IDictionary<") ||
                fullName.StartsWith("System.Collections.Generic.IReadOnlyDictionary<"))
                return CollectionKind.Dictionary;

            // Stack
            if (fullName.StartsWith("System.Collections.Generic.Stack<"))
                return CollectionKind.Stack;

            // Queue
            if (fullName.StartsWith("System.Collections.Generic.Queue<"))
                return CollectionKind.Queue;

            // LinkedList
            if (fullName.StartsWith("System.Collections.Generic.LinkedList<"))
                return CollectionKind.LinkedList;

            // ObservableCollection
            if (fullName.StartsWith("System.Collections.ObjectModel.ObservableCollection<"))
                return CollectionKind.ObservableCollection;

            // SortedSet
            if (fullName.StartsWith("System.Collections.Generic.SortedSet<"))
                return CollectionKind.SortedSet;

            // HashSet, ISet, IReadOnlySet -> HashSet
            if (fullName.StartsWith("System.Collections.Generic.HashSet<") ||
                fullName.StartsWith("System.Collections.Generic.ISet<") ||
                fullName.StartsWith("System.Collections.Generic.IReadOnlySet<"))
                return CollectionKind.HashSet;

            // List-like collections (including interfaces)
            if (fullName.StartsWith("System.Collections.Generic.List<") ||
                fullName.StartsWith("System.Collections.Generic.IList<") ||
                fullName.StartsWith("System.Collections.Generic.ICollection<") ||
                fullName.StartsWith("System.Collections.Generic.IEnumerable<") ||
                fullName.StartsWith("System.Collections.Generic.IReadOnlyList<") ||
                fullName.StartsWith("System.Collections.Generic.IReadOnlyCollection<"))
                return CollectionKind.List;
        }

        return CollectionKind.Unknown;
    }

    private static ITypeSymbol? GetCollectionElementType(ITypeSymbol type)
    {
        if (type is IArrayTypeSymbol arrayType)
            return arrayType.ElementType;

        if (type is INamedTypeSymbol namedType && namedType.TypeArguments.Length == 1)
            return namedType.TypeArguments[0];

        return null;
    }

    private static bool IsComplexType(ITypeSymbol type)
    {
        if (type.TypeKind == TypeKind.Enum) return false;
        if (IsSimpleType(type)) return false;
        if (IsCollectionType(type)) return false;
        if (type.SpecialType != SpecialType.None) return false;

        return type.TypeKind == TypeKind.Class || type.TypeKind == TypeKind.Struct;
    }

    private static bool compilation_IsAssignable(ITypeSymbol source, ITypeSymbol dest)
    {
        // Simple check - for full check would need Compilation.ClassifyConversion
        if (SymbolEqualityComparer.Default.Equals(source, dest))
            return true;

        // Check if dest is base class of source
        var current = source.BaseType;
        while (current != null)
        {
            if (SymbolEqualityComparer.Default.Equals(current, dest))
                return true;
            current = current.BaseType;
        }

        // Check interfaces
        foreach (var iface in source.AllInterfaces)
        {
            if (SymbolEqualityComparer.Default.Equals(iface, dest))
                return true;
        }

        return false;
    }

    /// <summary>
    /// v10.0.0: Normalizes type names for comparison (e.g., "string" -> "System.String").
    /// </summary>
    private static string NormalizeTypeName(string typeName)
    {
        return typeName switch
        {
            "string" => "System.String",
            "int" => "System.Int32",
            "long" => "System.Int64",
            "short" => "System.Int16",
            "byte" => "System.Byte",
            "sbyte" => "System.SByte",
            "uint" => "System.UInt32",
            "ulong" => "System.UInt64",
            "ushort" => "System.UInt16",
            "float" => "System.Single",
            "double" => "System.Double",
            "decimal" => "System.Decimal",
            "bool" => "System.Boolean",
            "char" => "System.Char",
            "object" => "System.Object",
            _ => typeName
        };
    }

    /// <summary>
    /// v10.0.0: Gets the type name suitable for transform lookup.
    /// </summary>
    private static string GetTypeNameForTransform(ITypeSymbol? type)
    {
        if (type == null) return "";
        return type.ToDisplayString();
    }

    /// <summary>
    /// v10.0.0: Applies type transformation if configured.
    /// </summary>
    private static string ApplyTransform(string valueExpr, ITypeSymbol? type, Dictionary<string, string> transformsByType)
    {
        if (type == null || transformsByType.Count == 0)
            return valueExpr;

        var typeName = GetTypeNameForTransform(type);
        if (transformsByType.TryGetValue(typeName, out var transformExpr))
        {
            // Replace {0} placeholder with the value expression
            return string.Format(transformExpr, valueExpr);
        }

        // Check if it's a nullable type and apply transform to the underlying type
        var underlying = GetUnderlyingType(type);
        if (underlying != null)
        {
            var underlyingTypeName = GetTypeNameForTransform(underlying);
            if (transformsByType.TryGetValue(underlyingTypeName, out var underlyingTransformExpr))
            {
                // For nullable types, need to handle null case
                return string.Format(underlyingTransformExpr, valueExpr);
            }
        }

        return valueExpr;
    }

    #endregion
}
